#!/bin/sh -e
# Autogenerated by 'mkbuild'; DO NOT EDIT!

USAGE="Usage: $0 asan|clang|coverage|tsan|ubsan|vanilla"
if [ $# -ne 1 ]; then
  echo "$USAGE" 1>&2
  exit 1
fi

docker run --cap-add=NET_ADMIN \
          -e CODECOV_TOKEN=$CODECOV_TOKEN \
          -e TRAVIS_BRANCH=$TRAVIS_BRANCH \
          -v "$(pwd):/mk" \
          -t bassosimone/mk-debian \
          /mk/.ci/docker/run.sh "$1"
